In [4]:
import requests
import pandas as pd

In [3]:
#obtener y conectar con los datos del API
url = "https://pokeapi.co/api/v2/pokemon/pikachu"
response = requests.get(url)
data = response.json()
#acceder al nombre
nombre = data['name']
print(f"Nombre: {nombre}")
#acceder a las estadisticas
stats = data['stats']
for stat in stats:
    stat_name = stat['stat']['name']
    base_stat = stat['base_stat']
    print(f"{stat_name.capitalize()}: {base_stat}")
#acceder a los tipos
types = data['types']
for tipo in types:
    type_name = tipo['type']['name']
    print(f"Tipo: {type_name}")

Nombre: pikachu
Hp: 35
Attack: 55
Defense: 40
Special-attack: 50
Special-defense: 50
Speed: 90
Tipo: electric

In [6]:
#convertir estadisticas en data frame
stats_df = pd.DataFrame([{
    'stat': stat['stat']['name'],
    'value': stat['base_stat']
} for stat in stats])

print("Estadisticas de Pikachu:")
display(stats_df)

Estadisticas de Pikachu:

              stat  value
0               hp     35
1           attack     55
2          defense     40
3   special-attack     50
4  special-defense     50
5            speed     90

In [9]:
##procesamientos complejos
##traer datos de varios pokemones
pokemons = ['pikachu','bulbasaur','charmander']
all_stats = []
for pokemon in pokemons:
    url = f"https://pokeapi.co/api/v2/pokemon/{pokemon}"
    response = requests.get(url)
    data = response.json()

    #acceder a las estadisticas
    for stat in data['stats']:
        all_stats.append({
            'pokemon': data['name'],
            'stat': stat['stat']['name'],
            'value': stat['base_stat']
        })

print(all_stats)

[{'pokemon': 'pikachu', 'stat': 'hp', 'value': 35}, {'pokemon': 'pikachu', 'stat': 'attack', 'value': 55}, {'pokemon': 'pikachu', 'stat': 'defense', 'value': 40}, {'pokemon': 'pikachu', 'stat': 'special-attack', 'value': 50}, {'pokemon': 'pikachu', 'stat': 'special-defense', 'value': 50}, {'pokemon': 'pikachu', 'stat': 'speed', 'value': 90}, {'pokemon': 'bulbasaur', 'stat': 'hp', 'value': 45}, {'pokemon': 'bulbasaur', 'stat': 'attack', 'value': 49}, {'pokemon': 'bulbasaur', 'stat': 'defense', 'value': 49}, {'pokemon': 'bulbasaur', 'stat': 'special-attack', 'value': 65}, {'pokemon': 'bulbasaur', 'stat': 'special-defense', 'value': 65}, {'pokemon': 'bulbasaur', 'stat': 'speed', 'value': 45}, {'pokemon': 'charmander', 'stat': 'hp', 'value': 39}, {'pokemon': 'charmander', 'stat': 'attack', 'value': 52}, {'pokemon': 'charmander', 'stat': 'defense', 'value': 43}, {'pokemon': 'charmander', 'stat': 'special-attack', 'value': 60}, {'pokemon': 'charmander', 'stat': 'special-defense', 'value': 50}, {'pokemon': 'charmander', 'stat': 'speed', 'value': 65}]

In [12]:
#conversion a data frame
all_stats_df = pd.DataFrame(all_stats)
display(all_stats_df)

       pokemon             stat  value
0      pikachu               hp     35
1      pikachu           attack     55
2      pikachu          defense     40
3      pikachu   special-attack     50
4      pikachu  special-defense     50
5      pikachu            speed     90
6    bulbasaur               hp     45
7    bulbasaur           attack     49
8    bulbasaur          defense     49
9    bulbasaur   special-attack     65
10   bulbasaur  special-defense     65
11   bulbasaur            speed     45
12  charmander               hp     39
13  charmander           attack     52
14  charmander          defense     43
15  charmander   special-attack     60
16  charmander  special-defense     50
17  charmander            speed     65

In [14]:
#mejorar el data frame con pivotes
pivot_df = all_stats_df.pivot_table(index='pokemon', columns='stat', values='value', aggfunc='mean')
display(pivot_df)

stat        attack  defense    hp  special-attack  special-defense  speed
pokemon
bulbasaur     49.0     49.0  45.0            65.0             65.0   45.0
charmander    52.0     43.0  39.0            60.0             50.0   65.0
pikachu       55.0     40.0  35.0            50.0             50.0   90.0